### ISSUE TITLE
Implement All Launches

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#23]
Reference: https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches.md#all-launches-launchesall

**Comment by ludamillion** [comment]
@rodolfobandeira Taking a swing at this. I've made the code changes necessary but haven't added tests yet. That's next on my plate.

Beyond adding an `all` method to `SPACEX::Launches` I updated `SPACEX::BaseRequest` to properly handle the situation where the response body is an array rather than a hash.
